const initialChairs = [

    {
        id: 1,
        image: {
            img:"https://ii1.pepperfry.com/media/catalog/product/l/o/1100x1210/loop-angeles-b-outdoor-bar-stool-in-jute-finish-loop-angeles-b-outdoor-bar-stool-in-jute-finish-5hjv9s.jpg",
            img1:"https://ii1.pepperfry.com/media/catalog/product/l/o/1100x1210/loop-angeles-b-outdoor-bar-stool-in-jute-finish-loop-angeles-b-outdoor-bar-stool-in-jute-finish-5hjv9s.jpg",
            img2:"https://ii1.pepperfry.com/media/catalog/product/d/e/764x840/derby-fabric-bar-stools-in-grey-colour-derby-fabric-bar-stools-in-grey-colour-qeg5jr.jpg",
            img3:"https://ii1.pepperfry.com/media/catalog/product/d/e/764x840/derby-fabric-bar-stools-in-grey-colour-derby-fabric-bar-stools-in-grey-colour-tdxmx1.jpg",
            img4:"https://ii1.pepperfry.com/media/catalog/product/d/e/764x840/derby-fabric-bar-stools-in-grey-colour-derby-fabric-bar-stools-in-grey-colour-tdxmx1.jpg",
            img5:"https://ii1.pepperfry.com/media/catalog/product/d/e/764x840/derby-fabric-bar-stools-in-grey-colour-derby-fabric-bar-stools-in-grey-colour-inu4mu.jpg",
            img6:"https://ii1.pepperfry.com/media/catalog/product/d/e/764x840/derby-fabric-bar-stools-in-grey-colour-derby-fabric-bar-stools-in-grey-colour-xwyv89.jpg",
            img7:"https://ii1.pepperfry.com/media/catalog/product/d/e/764x840/derby-fabric-bar-stools-in-grey-colour-derby-fabric-bar-stools-in-grey-colour-fwg77r.jpg",
            img8:"https://ii1.pepperfry.com/media/catalog/product/d/e/764x840/derby-fabric-bar-stools-in-grey-colour-derby-fabric-bar-stools-in-grey-colour-zhjlwk.jpg",
        },
        productName: 'Derby Fabric Bar Stools in Grey Colour,',
        productBrand:"By Durian",
        price: 6890,

        productDetails:{
            brand:"Durian",
            assembly:"Carpenter Assembly",
            dimensionCM:"H 91 x W 46 x D 48",
            dimensionIC:"H 36 x W 18 x D 19",
            material:"Fabric",
            room:"Living Room",
            height:26,
            warranty:"60 Months' Warranty",
            weight:"9.6 KG",
            sku:"FN2148038-S-PM25634",
        }
    },
    {
        id: 2,
        image: {
            img:"https://ii1.pepperfry.com/media/catalog/product/h/o/764x840/home-living-eliot-full-back-bar-chair-in-white-colour-by-finch-fox-home-living-eliot-full-back-bar-c-nffvvk.jpg",
            img1:"https://ii1.pepperfry.com/media/catalog/product/h/o/764x840/home-living-eliot-full-back-bar-chair-in-white-colour-by-finch-fox-home-living-eliot-full-back-bar-c-nffvvk.jpg",
            img2:"https://ii1.pepperfry.com/media/catalog/product/h/o/764x840/home-living-eliot-full-back-bar-chair-in-white-colour-by-finch-fox-home-living-eliot-full-back-bar-c-9uc4pg.jpg",
            img3:"https://ii1.pepperfry.com/media/catalog/product/h/o/764x840/home-living-eliot-full-back-bar-stool-in-white-colour-by-finch-fox-home-living-eliot-full-back-bar-s-ucie4y.jpg",
            img4:"https://ii1.pepperfry.com/media/catalog/product/h/o/764x840/home-living-eliot-full-back-bar-stool-in-white-colour-by-finch-fox-home-living-eliot-full-back-bar-s-xxro7z.jpg",
            img5:"https://ii1.pepperfry.com/media/catalog/product/h/o/764x840/home-living-eliot-full-back-bar-stool-in-white-colour-by-finch-fox-home-living-eliot-full-back-bar-s-sxn0n7.jpg",
            img6:"https://ii1.pepperfry.com/media/catalog/product/h/o/764x840/home-living-eliot-full-back-bar-stool-in-white-colour-by-finch-fox-home-living-eliot-full-back-bar-s-rw4ds9.jpg",
            img7:"https://ii1.pepperfry.com/media/catalog/product/h/o/764x840/home-living-eliot-full-back-bar-stool-in-white-colour-by-finch-fox-home-living-eliot-full-back-bar-s-vyej1e.jpg",
            img8:"https://ii1.pepperfry.com/media/catalog/product/h/o/764x840/home-living-eliot-full-back-bar-stool-in-white-colour-by-finch-fox-home-living-eliot-full-back-bar-s-learkj.jpg",
        },
        productName: 'Dora Solid Wood Bar Stool in White Finish,',
        productBrand:"By Finch Fox",
        price: 6299,
        productDetails:{
            brand:"Finch Fox",
            assembly:"Self Assembly",
            dimensionCM:"H 102 x W 56 x D 56",
            dimensionIC:"H 40 x W 21.5 x D 21.5 ; Seating Height: 28(all dimensions are in inches)",
            material:"Beech Wood",
            room:"Bar",
            height:28,
            warranty:"12 Months' Warranty",
            weight:"9.3 KG",
            sku:"FN1777185-S-PM39400",
        }
    },
    {
        id: 3,
        image: {
            img:"https://ii1.pepperfry.com/media/catalog/product/s/c/1100x1210/scandinavian-eames-high-bar-chair-in-red-colour-by-finch-fox-scandinavian-eames-high-bar-chair-in-re-kt5weh.jpg",
            img1:"https://ii1.pepperfry.com/media/catalog/product/s/c/1100x1210/scandinavian-eames-high-bar-chair-in-red-colour-by-finch-fox-scandinavian-eames-high-bar-chair-in-re-kt5weh.jpg",
            img2:"https://ii1.pepperfry.com/media/catalog/product/s/c/764x840/scandinavian-eames-high-bar-chair-in-red-colour-by-finch-fox-scandinavian-eames-high-bar-chair-in-re-l8sdj0.jpg",
            img3:"https://ii1.pepperfry.com/media/catalog/product/s/c/764x840/scandinavian-eames-high-bar-chair-in-red-colour-by-finch-fox-scandinavian-eames-high-bar-chair-in-re-gkqzvz.jpg",
            img4:"https://ii1.pepperfry.com/media/catalog/product/s/c/764x840/scandinavian-eames-high-bar-chair-in-red-colour-by-finch-fox-scandinavian-eames-high-bar-chair-in-re-vqqkso.jpg",
            img5:"https://ii1.pepperfry.com/media/catalog/product/s/c/764x840/scandinavian-eames-high-bar-chair-in-red-colour-by-finch-fox-scandinavian-eames-high-bar-chair-in-re-5n9jma.jpg",
            img6:"",
            img7:"",
            img8:"",
        },
        productName: 'Bentley Fabric Bar Stools in Red Colour,',
        productBrand:"By Finch Fox",
        price: 5999,

        productDetails:{
            brand:"Finch Fox ",
            assembly:"Self Assembly",
            dimensionCM:"H 107 x W 53 x D 53",
            dimensionIC:"H 42 x W 21 x D 21",
            material:"Fabric",
            room:"Bar",
            height:18,
            warranty:"12 Months' Warranty",
            weight:"7.5kg",
            sku:"FN1777203-S-PM39400",
        }
    },

    {
        id: 4,
        image: {
            img:"",
            img1:"",
            img2:"",
            img3:"",
            img4:"",
            img5:"",
            img6:"",
            img7:"",
            img8:"",
        },
        productName: 'Alfredo 1 Seat Sofa',
        price: 3200,

        productDetails:{
            brand:"",
            assembly:"",
            dimensionCM:"",
            dimensionIC:"",
            material:"",
            room:"",
            height:"",
            warranty:"",
            weight:"",
            sku:"",
        }

    },

    {
        id: 5,
        image: {
            img:"",
            img1:"",
            img2:"",
            img3:"",
            img4:"",
            img5:"",
            img6:"",
            img7:"",
            img8:"",
        },
        productName: 'Alfredo 1 Seat Sofa',
        price: 3200 ,

        productDetails:{
            brand:"",
            assembly:"",
            dimensionCM:"",
            dimensionIC:"",
            material:"",
            room:"",
            height:"",
            warranty:"",
            weight:"",
            sku:"",
        }
    },


    {
        id: 6,
        image: {
            img:"",
            img1:"",
            img2:"",
            img3:"",
            img4:"",
            img5:"",
            img6:"",
            img7:"",
            img8:"",
        },
        productName: 'Alfredo 1 Seat Sofa',
        price: 3200 ,

        productDetails:{
            brand:"",
            assembly:"",
            dimensionCM:"",
            dimensionIC:"",
            material:"",
            room:"",
            height:"",
            warranty:"",
            weight:"",
            sku:"",
        }
    },

    {
        id: 7,
        image: {
            img:"",
            img1:"",
            img2:"",
            img3:"",
            img4:"",
            img5:"",
            img6:"",
            img7:"",
            img8:"",
        },
        productName: 'Alfredo 1 Seat Sofa',
        price: 3200,

        productDetails:{
            brand:"",
            assembly:"",
            dimensionCM:"",
            dimensionIC:"",
            material:"",
            room:"",
            height:"",
            warranty:"",
            weight:"",
            sku:"",
        }
    },
    {
        id: 8,
        image: {
            img:"",
            img1:"",
            img2:"",
            img3:"",
            img4:"",
            img5:"",
            img6:"",
            img7:"",
            img8:"",
        },
        productName: 'Alfredo 1 Seat Sofa',
        price: 3200 ,

        productDetails:{
            brand:"",
            assembly:"",
            dimensionCM:"",
            dimensionIC:"",
            material:"",
            room:"",
            height:"",
            warranty:"",
            weight:"",
            sku:"",
        }
    },
    {
        id: 9,
        image: {
            img:"",
            img1:"",
            img2:"",
            img3:"",
            img4:"",
            img5:"",
            img6:"",
            img7:"",
            img8:"",
        },
        productName: 'Alfredo 1 Seat Sofa',
        price: "$30.00" ,

        productDetails:{
            brand:"",
            assembly:"",
            dimensionCM:"",
            dimensionIC:"",
            material:"",
            room:"",
            height:"",
            warranty:"",
            weight:"",
            sku:"",
        }
    },
    {
        id: 10,
        image: {
            img:"",
            img1:"",
            img2:"",
            img3:"",
            img4:"",
            img5:"",
            img6:"",
            img7:"",
            img8:"",
        },
        productName: 'Alfredo 1 Seat Sofa',
        price: 3200 ,

        productDetails:{
            brand:"",
            assembly:"",
            dimensionCM:"",
            dimensionIC:"",
            material:"",
            room:"",
            height:"",
            warranty:"",
            weight:"",
            sku:"",
        }
    },
    {
        id: 11,
        image: {
            img:"",
            img1:"",
            img2:"",
            img3:"",
            img4:"",
            img5:"",
            img6:"",
            img7:"",
            img8:"",
        },
        productName: 'Alfredo 1 Seat Sofa',
        price: 3200 ,

        productDetails:{
            brand:"",
            assembly:"",
            dimensionCM:"",
            dimensionIC:"",
            material:"",
            room:"",
            height:"",
            warranty:"",
            weight:"",
            sku:"",
        }
    },

    {
        id: 12,
        image: {
            img:"",
            img1:"",
            img2:"",
            img3:"",
            img4:"",
            img5:"",
            img6:"",
            img7:"",
            img8:"",
        },
        productName: 'Alfredo 1 Seat Sofa',
        price: 3200 ,

        productDetails:{
            brand:"",
            assembly:"",
            dimensionCM:"",
            dimensionIC:"",
            material:"",
            room:"",
            height:"",
            warranty:"",
            weight:"",
            sku:"",
        }
    },

]
export default initialChairs
