const initialChairs = [

    {
        id: 1,
        image: {
            img:"https://ii1.pepperfry.com/media/catalog/product/l/o/1100x1210/loop-angeles-b-outdoor-bar-stool-in-jute-finish-loop-angeles-b-outdoor-bar-stool-in-jute-finish-5hjv9s.jpg",
            img1:"https://ii1.pepperfry.com/media/catalog/product/l/o/1100x1210/loop-angeles-b-outdoor-bar-stool-in-jute-finish-loop-angeles-b-outdoor-bar-stool-in-jute-finish-5hjv9s.jpg",
            img2:"https://ii1.pepperfry.com/media/catalog/product/d/e/764x840/derby-fabric-bar-stools-in-grey-colour-derby-fabric-bar-stools-in-grey-colour-qeg5jr.jpg",
            img3:"https://ii1.pepperfry.com/media/catalog/product/d/e/764x840/derby-fabric-bar-stools-in-grey-colour-derby-fabric-bar-stools-in-grey-colour-tdxmx1.jpg",
            img4:"https://ii1.pepperfry.com/media/catalog/product/d/e/764x840/derby-fabric-bar-stools-in-grey-colour-derby-fabric-bar-stools-in-grey-colour-tdxmx1.jpg",
            img5:"https://ii1.pepperfry.com/media/catalog/product/d/e/764x840/derby-fabric-bar-stools-in-grey-colour-derby-fabric-bar-stools-in-grey-colour-inu4mu.jpg",
            img6:"https://ii1.pepperfry.com/media/catalog/product/d/e/764x840/derby-fabric-bar-stools-in-grey-colour-derby-fabric-bar-stools-in-grey-colour-xwyv89.jpg",
            img7:"https://ii1.pepperfry.com/media/catalog/product/d/e/764x840/derby-fabric-bar-stools-in-grey-colour-derby-fabric-bar-stools-in-grey-colour-fwg77r.jpg",
            img8:"https://ii1.pepperfry.com/media/catalog/product/d/e/764x840/derby-fabric-bar-stools-in-grey-colour-derby-fabric-bar-stools-in-grey-colour-zhjlwk.jpg",
        },
        productName: 'Derby Fabric Bar Stools in Grey Colour,',
        productBrand:"By Durian",
        price: 6890,

        productDetails:{
            brand:"Durian",
            assembly:"Carpenter Assembly",
            dimensionCM:"H 91 x W 46 x D 48",
            dimensionIC:"H 36 x W 18 x D 19",
            material:"Fabric",
            room:"Living Room",
            height:26,
            warranty:"60 Months' Warranty",
            weight:"9.6 KG",
            sku:"FN2148038-S-PM25634",
        }
    },
    {
        id: 2,
        image: {
            img:"https://ii1.pepperfry.com/media/catalog/product/h/o/764x840/home-living-eliot-full-back-bar-chair-in-white-colour-by-finch-fox-home-living-eliot-full-back-bar-c-nffvvk.jpg",
            img1:"https://ii1.pepperfry.com/media/catalog/product/h/o/764x840/home-living-eliot-full-back-bar-chair-in-white-colour-by-finch-fox-home-living-eliot-full-back-bar-c-nffvvk.jpg",
            img2:"https://ii1.pepperfry.com/media/catalog/product/h/o/764x840/home-living-eliot-full-back-bar-chair-in-white-colour-by-finch-fox-home-living-eliot-full-back-bar-c-9uc4pg.jpg",
            img3:"https://ii1.pepperfry.com/media/catalog/product/h/o/764x840/home-living-eliot-full-back-bar-stool-in-white-colour-by-finch-fox-home-living-eliot-full-back-bar-s-ucie4y.jpg",
            img4:"https://ii1.pepperfry.com/media/catalog/product/h/o/764x840/home-living-eliot-full-back-bar-stool-in-white-colour-by-finch-fox-home-living-eliot-full-back-bar-s-xxro7z.jpg",
            img5:"https://ii1.pepperfry.com/media/catalog/product/h/o/764x840/home-living-eliot-full-back-bar-stool-in-white-colour-by-finch-fox-home-living-eliot-full-back-bar-s-sxn0n7.jpg",
            img6:"https://ii1.pepperfry.com/media/catalog/product/h/o/764x840/home-living-eliot-full-back-bar-stool-in-white-colour-by-finch-fox-home-living-eliot-full-back-bar-s-rw4ds9.jpg",
            img7:"https://ii1.pepperfry.com/media/catalog/product/h/o/764x840/home-living-eliot-full-back-bar-stool-in-white-colour-by-finch-fox-home-living-eliot-full-back-bar-s-vyej1e.jpg",
            img8:"https://ii1.pepperfry.com/media/catalog/product/h/o/764x840/home-living-eliot-full-back-bar-stool-in-white-colour-by-finch-fox-home-living-eliot-full-back-bar-s-learkj.jpg",
        },
        productName: 'Dora Solid Wood Bar Stool in White Finish,',
        productBrand:"By Finch Fox",
        price: 6299,
        productDetails:{
            brand:"Finch Fox",
            assembly:"Self Assembly",
            dimensionCM:"H 102 x W 56 x D 56",
            dimensionIC:"H 40 x W 21.5 x D 21.5 ; Seating Height: 28(all dimensions are in inches)",
            material:"Beech Wood",
            room:"Bar",
            height:28,
            warranty:"12 Months' Warranty",
            weight:"9.3 KG",
            sku:"FN1777185-S-PM39400",
        }
    },
    {
        id: 3,
        image: {
            img:"https://ii1.pepperfry.com/media/catalog/product/s/c/1100x1210/scandinavian-eames-high-bar-chair-in-red-colour-by-finch-fox-scandinavian-eames-high-bar-chair-in-re-kt5weh.jpg",
            img1:"https://ii1.pepperfry.com/media/catalog/product/s/c/1100x1210/scandinavian-eames-high-bar-chair-in-red-colour-by-finch-fox-scandinavian-eames-high-bar-chair-in-re-kt5weh.jpg",
            img2:"https://ii1.pepperfry.com/media/catalog/product/s/c/764x840/scandinavian-eames-high-bar-chair-in-red-colour-by-finch-fox-scandinavian-eames-high-bar-chair-in-re-l8sdj0.jpg",
            img3:"https://ii1.pepperfry.com/media/catalog/product/s/c/764x840/scandinavian-eames-high-bar-chair-in-red-colour-by-finch-fox-scandinavian-eames-high-bar-chair-in-re-gkqzvz.jpg",
            img4:"https://ii1.pepperfry.com/media/catalog/product/s/c/764x840/scandinavian-eames-high-bar-chair-in-red-colour-by-finch-fox-scandinavian-eames-high-bar-chair-in-re-vqqkso.jpg",
            img5:"https://ii1.pepperfry.com/media/catalog/product/s/c/764x840/scandinavian-eames-high-bar-chair-in-red-colour-by-finch-fox-scandinavian-eames-high-bar-chair-in-re-5n9jma.jpg",
            img6:"",
            img7:"",
            img8:"",
        },
        productName: 'Bentley Fabric Bar Stools in Red Colour,',
        productBrand:"By Finch Fox",
        price: 5999,

        productDetails:{
            brand:"Finch Fox ",
            assembly:"Self Assembly",
            dimensionCM:"H 107 x W 53 x D 53",
            dimensionIC:"H 42 x W 21 x D 21",
            material:"Fabric",
            room:"Bar",
            height:18,
            warranty:"12 Months' Warranty",
            weight:"7.5kg",
            sku:"FN1777203-S-PM39400",
        }
    },

    {
        id: 4,
        image: {
            img:"https://ii1.pepperfry.com/media/catalog/product/h/a/764x840/harold-sheesham-wood-rocking-chair-in-honey-oak-finish-harold-sheesham-wood-rocking-chair-in-honey-o-ewyfli.jpg",
            img1:"https://ii1.pepperfry.com/media/catalog/product/h/a/764x840/harold-solid-wood-rocking-chair-in-honey-oak-finish-by-amberville-harold-solid-wood-rocking-chair-in-1pgyih.jpg",
            img2:"https://ii1.pepperfry.com/media/catalog/product/h/a/764x840/harold-sheesham-wood-rocking-chair-in-scratch-resistant-honey-oak-finish-harold-sheesham-wood-rockin-ypqnjy.jpg",
            img3:"https://ii1.pepperfry.com/media/catalog/product/h/a/764x840/harold-solid-wood-rocking-chair-in-honey-oak-finish-by-amberville-harold-solid-wood-rocking-chair-in-2wriwp.jpg",
            img4:"https://ii1.pepperfry.com/media/catalog/product/h/a/764x840/harold-solid-wood-rocking-chair-in-honey-oak-finish-by-amberville-harold-solid-wood-rocking-chair-in-zhzgsc.jpg",
            img5:"https://ii1.pepperfry.com/media/catalog/product/h/a/764x840/harold-solid-wood-rocking-chair-in-honey-oak-finish-by-amberville-harold-solid-wood-rocking-chair-in-wcb8bi.jpg",
            img6:"https://ii1.pepperfry.com/media/catalog/product/h/a/764x840/harold-solid-wood-rocking-chair-in-honey-oak-finish-by-amberville-harold-solid-wood-rocking-chair-in-tub1bh.jpg",
            img7:"https://ii1.pepperfry.com/media/catalog/product/h/a/764x840/harold-solid-wood-rocking-chair-in-honey-oak-finish-by-amberville-harold-solid-wood-rocking-chair-in-2nzgfo.jpg",
            img8:"https://ii1.pepperfry.com/media/catalog/product/h/a/764x840/harold-solid-wood-rocking-chair-in-honey-oak-finish-by-amberville-harold-solid-wood-rocking-chair-in-vnwpbe.jpg",
        },
        productName: 'Harold Sheesham Wood Rocking Chair in Scratch Resistant Honey Oak Finish,',
        productBrand:"By Amberville from Pepperfry",
        price: 15999,

        productDetails:{
            brand:"Amberville from Pepperfry",
            assembly:"Carpenter Assembly",
            dimensionCM:"H 119 x W 56 x D 97",
            dimensionIC:"H 47 x W 22 x D 38",
            material:"Sheesham Wood",
            room:"Living Room",
            height:18,
            warranty:"36 Months' Warranty",
            weight:"25 KG",
            sku:"FM1062952-S-PM32431",
        }

    },

    {
        id: 5,
        image: {
            img:"https://ii1.pepperfry.com/media/catalog/product/t/o/764x840/touffy-rocking-chair-in-brown-silver-colour-by-dzyn-furnitures-touffy-rocking-chair-in-brown-silver--my7vac.jpg",
            img1:"https://ii1.pepperfry.com/media/catalog/product/t/o/764x840/touffy-rocking-chair-in-brown-silver-colour-by-dzyn-furnitures-touffy-rocking-chair-in-brown-silver--my7vac.jpg",
            img2:"https://ii1.pepperfry.com/media/catalog/product/t/o/764x840/touffy-rocking-chair-in-brown-silver-colour-by-dzyn-furnitures-touffy-rocking-chair-in-brown-silver--s3khk8.jpg",
            img3:"https://ii1.pepperfry.com/media/catalog/product/t/o/764x840/touffy-rocking-chair-in-brown-silver-colour-by-dzyn-furnitures-touffy-rocking-chair-in-brown-silver--khbzpr.jpg",
            img4:"https://ii1.pepperfry.com/media/catalog/product/t/o/764x840/touffy-rocking-chair-in-brown-silver-colour-by-dzyn-furnitures-touffy-rocking-chair-in-brown-silver--tcxatl.jpg",
            img5:"https://ii1.pepperfry.com/media/catalog/product/t/o/764x840/touffy-rocking-chair-in-brown-silver-colour-by-dzyn-furnitures-touffy-rocking-chair-in-brown-silver--my7vac.jpg",
            img6:"https://ii1.pepperfry.com/media/catalog/product/t/o/764x840/touffy-rocking-chair-in-brown-silver-colour-by-dzyn-furnitures-touffy-rocking-chair-in-brown-silver--thm8we.jpg",
            img7:"https://ii1.pepperfry.com/media/catalog/product/t/o/764x840/touffy-rocking-chair-in-brown-silver-colour-by-dzyn-furnitures-touffy-rocking-chair-in-brown-silver--fejnjv.jpg",
            img8:"https://ii1.pepperfry.com/media/catalog/product/t/o/764x840/touffy-rocking-chair-in-brown-silver-colour-by-dzyn-furnitures-touffy-rocking-chair-in-brown-silver--bbl4r0.jpg",
        },
        productName: 'Touffy Solid Wood Rocking Chair in Beige Colour',
        productBrand:"By DZYN Furnitures",
        price: 24990,

        productDetails:{
            brand:"DZYN Furnitures",
            assembly:"Assembly by Brand (Installation in 72 hours)",
            dimensionCM:"H 99 x W 58 x D 91",
            dimensionIC:"H 39 x W 23 x D 36",
            material:"Teak Wood",
            room:"Living Room",
            height:12,
            warranty:"6 Months' Warranty",
            weight:"18 KG",
            sku:"FN1963859-S-PM35171",
        }
    },


    {
        id: 6,
        image: {
            img:"https://ii1.pepperfry.com/media/catalog/product/t/u/1100x1210/tucson-sheesham-wood-rocking-chair-in-rustic-teak-finish-by-woodsworth-tucson-sheesham-wood-rocking--0uruip.jpg",
            img1:"https://ii1.pepperfry.com/media/catalog/product/t/u/1100x1210/tucson-sheesham-wood-rocking-chair-in-rustic-teak-finish-by-woodsworth-tucson-sheesham-wood-rocking--0uruip.jpg",
            img2:"https://ii1.pepperfry.com/media/catalog/product/t/u/764x840/tucson-sheesham-wood-rocking-chair-in-rustic-teak-finish-by-woodsworth-tucson-sheesham-wood-rocking--webfbw.jpg",
            img3:"https://ii1.pepperfry.com/media/catalog/product/t/u/764x840/tucson-sheesham-wood-rocking-chair-in-rustic-teak-finish-tucson-sheesham-wood-rocking-chair-in-rusti-8bsikx.jpg",
            img4:"https://ii1.pepperfry.com/media/catalog/product/t/u/764x840/tucson-sheesham-wood-rocking-chair-in-rustic-teak-finish-by-woodsworth-tucson-sheesham-wood-rocking--zda9gc.jpg",
            img5:"https://ii1.pepperfry.com/media/catalog/product/t/u/764x840/tucson-sheesham-wood-rocking-chair-in-rustic-teak-finish-by-woodsworth-tucson-sheesham-wood-rocking--0sti3y.jpg",
            img6:"https://ii1.pepperfry.com/media/catalog/product/t/u/764x840/tucson-sheesham-wood-rocking-chair-in-rustic-teak-finish-by-woodsworth-tucson-sheesham-wood-rocking--bx6wqm.jpg",
            img7:"https://ii1.pepperfry.com/media/catalog/product/t/u/764x840/tucson-sheesham-wood-rocking-chair-in-rustic-teak-finish-by-woodsworth-tucson-sheesham-wood-rocking--d9pmwr.jpg",
            img8:"https://ii1.pepperfry.com/media/catalog/product/t/u/764x840/tucson-sheesham-wood-rocking-chair-in-rustic-teak-finish-by-woodsworth-tucson-sheesham-wood-rocking--hdeeq3.jpg",
        },
        productName: 'Tucson Sheesham Wood Rocking Chair in Rustic Teak Finish',
        productBrand:"Woodsworth from Pepperfry",
        price: 18499 ,

        productDetails:{
            brand:"Woodsworth from Pepperfry",
            assembly:"No Assembly Required",
            dimensionCM:"H 104 x W 56 x D 104",
            dimensionIC:"H 41 x W 22 x D 41 ",
            material:"Sheesham Wood",
            room:"Living Room",
            height:16,
            warranty:"36 Months' Warranty",
            weight:"23 KG",
            sku:"FM1813879-S-WH34197",
        }
    },

    {
        id: 7,
        image: {
            img:"https://ii1.pepperfry.com/media/catalog/product/b/r/764x840/brenton-solid-wood-rocking-chair-in-brown---dark-blue-colour-brenton-solid-wood-rocking-chair-in-bro-juedut.jpg",
            img1:"https://ii1.pepperfry.com/media/catalog/product/b/r/764x840/brenton-solid-wood-rocking-chair-in-brown---dark-blue-colour-brenton-solid-wood-rocking-chair-in-bro-juedut.jpg",
            img2:"https://ii1.pepperfry.com/media/catalog/product/b/r/764x840/brenton-solid-wood-rocking-chair-in-brown---dark-blue-colour-brenton-solid-wood-rocking-chair-in-bro-fdduys.jpg",
            img3:"https://ii1.pepperfry.com/media/catalog/product/b/r/764x840/brenton-solid-wood-rocking-chair-in-brown---dark-blue-colour-brenton-solid-wood-rocking-chair-in-bro-fsyrpy.jpg",
            img4:"https://ii1.pepperfry.com/media/catalog/product/b/r/764x840/brenton-solid-wood-rocking-chair-in-brown---dark-blue-colour-brenton-solid-wood-rocking-chair-in-bro-hcnn1d.jpg",
            img5:"https://ii1.pepperfry.com/media/catalog/product/b/r/764x840/brenton-solid-wood-rocking-chair-in-brown---dark-blue-colour-brenton-solid-wood-rocking-chair-in-bro-jq0ill.jpg",
            img6:"https://ii1.pepperfry.com/media/catalog/product/b/r/764x840/brenton-solid-wood-rocking-chair-in-brown---dark-blue-colour-brenton-solid-wood-rocking-chair-in-bro-uxbsci.jpg",
            img7:"",
            img8:"",
        },
        productName: 'Brenton Solid Wood Rocking Chair in Brown & Dark Blue Colour',
        productBrand:"Durian",
        price: 12500,

        productDetails:{
            brand:"Durian",
            assembly:"Carpenter Assembly",
            dimensionCM:"H 72 x W 55 x D 77",
            dimensionIC:"H 28.5 x W 21.5 x D 30.5",
            material:"Beech Wood",
            room:"Living Room",
            height:19.5,
            warranty:"60 Months' Warranty",
            weight:"13 KG",
            sku:"FN1967206-S-PM25634",
        }
    },
    {
        id: 8,
        image: {
            img:"https://ii1.pepperfry.com/media/catalog/product/m/e/764x840/memsaab-fabric-rocking-chair-in-green-colour-memsaab-fabric-rocking-chair-in-green-colour-fnnmyg.jpg",
            img1:"https://ii1.pepperfry.com/media/catalog/product/m/e/764x840/memsaab-fabric-rocking-chair-in-green-colour-memsaab-fabric-rocking-chair-in-green-colour-fnnmyg.jpg",
            img2:"https://ii1.pepperfry.com/media/catalog/product/m/e/764x840/memsaab-fabric-rocking-chair-in-green-colour-memsaab-fabric-rocking-chair-in-green-colour-4t2euw.jpg",
            img3:"https://ii1.pepperfry.com/media/catalog/product/m/e/764x840/memsaab-fabric-rocking-chair-in-green-colour-memsaab-fabric-rocking-chair-in-green-colour-nbpdyr.jpg",
            img4:"https://ii1.pepperfry.com/media/catalog/product/m/e/764x840/memsaab-fabric-rocking-chair-in-green-colour-memsaab-fabric-rocking-chair-in-green-colour-yggjos.jpg",
            img5:"https://ii1.pepperfry.com/media/catalog/product/m/e/764x840/memsaab-fabric-rocking-chair-in-green-colour-memsaab-fabric-rocking-chair-in-green-colour-j3uajp.jpg",
            img6:"https://ii1.pepperfry.com/media/catalog/product/m/e/764x840/memsaab-fabric-rocking-chair-in-green-colour-memsaab-fabric-rocking-chair-in-green-colour-vzxwkn.jpg",
            img7:"https://ii1.pepperfry.com/media/catalog/product/m/e/764x840/memsaab-fabric-rocking-chair-in-green-colour-memsaab-fabric-rocking-chair-in-green-colour-xlfltr.jpg",
            img8:"",
        },
        productName: 'Memsaab Fabric Rocking Chair in Green Colour',
        productBrand:'By Chumbak',
        price: 26995 ,

        productDetails:{
            brand:"By Chumbak",
            assembly:"No Assembly Required",
            dimensionCM:"H 89 x W 66 x D 102",
            dimensionIC:"H 35 x W 26 x D 40",
            material:"Fabric",
            room:"Living Room",
            height:20,
            warranty:"12 Months' Warranty",
            weight:"28 KG",
            sku:"FN1963348-S-PM39425",
        }
    },
    // {
    //     id: 9,
    //     image: {
    //         img:"",
    //         img1:"",
    //         img2:"",
    //         img3:"",
    //         img4:"",
    //         img5:"",
    //         img6:"",
    //         img7:"",
    //         img8:"",
    //     },
    //     productName: 'Alfredo 1 Seat Sofa',
    //     price: "$30.00" ,

    //     productDetails:{
    //         brand:"",
    //         assembly:"",
    //         dimensionCM:"",
    //         dimensionIC:"",
    //         material:"",
    //         room:"",
    //         height:"",
    //         warranty:"",
    //         weight:"",
    //         sku:"",
    //     }
    // },
    // {
    //     id: 10,
    //     image: {
    //         img:"",
    //         img1:"",
    //         img2:"",
    //         img3:"",
    //         img4:"",
    //         img5:"",
    //         img6:"",
    //         img7:"",
    //         img8:"",
    //     },
    //     productName: 'Alfredo 1 Seat Sofa',
    //     price: 3200 ,

    //     productDetails:{
    //         brand:"",
    //         assembly:"",
    //         dimensionCM:"",
    //         dimensionIC:"",
    //         material:"",
    //         room:"",
    //         height:"",
    //         warranty:"",
    //         weight:"",
    //         sku:"",
    //     }
    // },
    // {
    //     id: 11,
    //     image: {
    //         img:"",
    //         img1:"",
    //         img2:"",
    //         img3:"",
    //         img4:"",
    //         img5:"",
    //         img6:"",
    //         img7:"",
    //         img8:"",
    //     },
    //     productName: 'Alfredo 1 Seat Sofa',
    //     price: 3200 ,

    //     productDetails:{
    //         brand:"",
    //         assembly:"",
    //         dimensionCM:"",
    //         dimensionIC:"",
    //         material:"",
    //         room:"",
    //         height:"",
    //         warranty:"",
    //         weight:"",
    //         sku:"",
    //     }
    // },

    // {
    //     id: 12,
    //     image: {
    //         img:"",
    //         img1:"",
    //         img2:"",
    //         img3:"",
    //         img4:"",
    //         img5:"",
    //         img6:"",
    //         img7:"",
    //         img8:"",
    //     },
    //     productName: 'Alfredo 1 Seat Sofa',
    //     price: 3200 ,

    //     productDetails:{
    //         brand:"",
    //         assembly:"",
    //         dimensionCM:"",
    //         dimensionIC:"",
    //         material:"",
    //         room:"",
    //         height:"",
    //         warranty:"",
    //         weight:"",
    //         sku:"",
    //     }
    // },

]
export default initialChairs
